---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: true
  hosts: all
  tasks:

    - name: Get config for Ubuntu devices
      vyos.vyos.vyos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
